<a href="https://colab.research.google.com/github/JimmyLundus/SQL-Projects/blob/main/Copy_of_Codemy_Python_Data_Analysis_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#python list
my_list = [1,2,3,4,5, "John", True]
my_list2 = [6,7,8, my_list]
print(my_list)
print(my_list2)



[1, 2, 3, 4, 5, 'John', True]
[6, 7, 8, [1, 2, 3, 4, 5, 'John', True]]


In [2]:
#Import Numpy
import numpy as np

In [ ]:
# Create a numpy array
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print (np1)
print(np1[2])




[0 1 2 3 4 5 6 7 8 9]
2


In [ ]:
#Shape - shows the number of elements in the array like the python len function
print(np1.shape)

(10,)


In [ ]:
# Arange -  allows us to created a numpy array with a certain number of items in it.
np2 = np.arange(10)
print(np2)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Step - creates a list with a defined "step" amount. Syntax is np.arange(starting value, ending value, step value)
np3 = np.arange(0,12,2)
print (np3)


[ 0  2  4  6  8 10]


In [ ]:
# Zeros (dummy data)
np4 = np.zeros(10)
print (np4)     #Results below show 0.blank. this is floating point and it actually leaves off the second zero!

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Multi-Dimensional Array with Zeros
np5 = np.zeros((2,10))
print (np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
# Full (Function)
np6 = np.full((10),6)
print (np6)

[6 6 6 6 6 6 6 6 6 6]


In [6]:
# Multi-Dimensional Array with Full
np7 = np.full((2, 10), 41)
np8= np.full((2, 10), "Bob")
print(np7)
print(np8)


[[41 41 41 41 41 41 41 41 41 41]
 [41 41 41 41 41 41 41 41 41 41]]
[['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']
 ['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']]


In [14]:
# Convert Python List to Numpy Array
# my_list
my_list = [1,2,3,4,5]
np9 = np.array(my_list)
print(np9) # If we print the full list from above in our array, it looks like
           # our old list,except items are each in quotations marks,since
           # everything was changed into a string when entered into the array!
           # printing just the numbers from the list above (new list) in an array
           # yields just numbers without quotation marks since python recognizes
           # them as integers now since they are not mixed with other stuff as
           # in the original list above.
           # when just printing the new list, the quotations marks disappear!
print(my_list) # Python list items are always seprated by commas!


[1 2 3 4 5]
[1, 2, 3, 4, 5]
