<a href="https://colab.research.google.com/github/JimmyLundus/SQL-Projects/blob/main/Copy_of_Codemy_Python_Data_Analysis_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#python list
my_list = [1,2,3,4,5, "John", True]
my_list2 = [6,7,8, my_list]

In [2]:
#Import Numpy
import numpy as np

In [ ]:
# Create a numpy array
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print (np1)
print(np1[2])




[0 1 2 3 4 5 6 7 8 9]
2


In [ ]:
#Shape - shows the number of elements in the array like the python len function
print(np1.shape)

(10,)


In [ ]:
# Arange -  allows us to created a numpy array with a certain number of items in it.
np2 = np.arange(10)
print(np2)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Step - creates a list with a defined "step" amount. Syntax is np.arange(starting value, ending value, step value)
np3 = np.arange(0,12,2)
print (np3)


[ 0  2  4  6  8 10]


In [ ]:
# Zeros (dummy data)
np4 = np.zeros(10)
print (np4)     #Results below show 0.blank. this is floating point and it actually leaves off the second zero!

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Multi-Dimensional Array with Zeros
np5 = np.zeros((2,10))
print (np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Full

In [ ]:
# Multi-Dimensional Array with Full

In [ ]:
# Convert Python List to Numpy Array